services:
  postgres:
    image: 'postgres'
    volumes:
      - "wb_pg_data:/var/lib/postgresql/data"
    extra_hosts:
      - "host.docker.internal:172.19.0.1"
    ports:
      - "25432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whatbot

volumes:
  wb_pg_data:
    driver: local
