[package]
name = "whatbot-io-discord"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
whatbot-core = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serenity = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
